#source 'http://production.cf.rubygems.org/'
source 'https://rubygems.org'

gem 'nokogiri'
gem 'sqlite3'
gem 'mysql2', :platforms => :ruby
gem 'json'
gem 'ffi'
gem 'bcrypt'
gem 'yajl-ruby'
gem 'thin'
gem 'RedCloth'
gem 'escape_utils'
gem 'posix-spawn', :platforms => :ruby
gem 'nokogumbo'
gem 'github-markdown'
gem 'rugged', :platforms => :ruby
gem 'charlock_holmes', :platforms => :ruby
gem 'unf_ext'
