source 'https://rubygems.org'

gem 'fast-stemmer'
gem 'hitimes'
gem 'redcarpet'
gem 'pg'
gem 'mysql2'
gem 'puma', :platforms => :ruby
gem 'kgio', :platforms => :ruby
gem 'raindrops', :platforms => :ruby
gem 'unicorn', :platforms => :ruby
