#!/bin/bash
set -e
source /system_shared/library.sh

header "Preparing"
if [[ "$ARCHITECTURE" = x86 ]]; then
	CHROOT_NAME=epel-5-i386
else
	CHROOT_NAME=epel-5-x86_64
fi
ROOT=/var/lib/mock/$CHROOT_NAME/root
run rm -rf $ROOT/system $ROOT/output
run mkdir $ROOT/system $ROOT/output
run cp /system/* $ROOT/system/
run cp /system_shared/* $ROOT/system/
if [[ -e /Gemfile ]]; then
	run cp /Gemfile $ROOT/system/
fi
if [[ -e /Gemfile.lock ]]; then
	run cp /Gemfile.lock $ROOT/system/
fi
echo "Dumping parameters"
echo $ARCHITECTURE > $ROOT/system/NAME
echo $APP_UID > $ROOT/system/APP_UID
echo $APP_GID > $ROOT/system/APP_GID
echo $RUBY_VERSION > $ROOT/system/RUBY_VERSION
echo $BUNDLER_VERSION > $ROOT/system/BUNDLER_VERSION
echo $CONCURRENCY > $ROOT/system/CONCURRENCY
echo $SETUP_SOURCE > $ROOT/system/SETUP_SOURCE
echo $COMPILE > $ROOT/system/COMPILE
echo $SANITY_CHECK_OUTPUT > $ROOT/system/SANITY_CHECK_OUTPUT
echo "Entering mock chroot"
run /system/setuser app /usr/bin/mock -r $CHROOT_NAME --quiet --shell /system/build-inside-mock
echo "Left mock chroot"
echo

header "Finalizing"
run chown $APP_UID:$APP_GID /output
run cp -dpR $ROOT/output/* /output/
run rm -rf $ROOT/system $ROOT/output
