#!/bin/bash
set -e
source /system/library.sh
ARCHITECTURE=`cat /system/ARCHITECTURE`

function download_and_extract()
{
	local BASENAME="$1"
	local URL="$2"
	local regex='\.bz2$'

	run rm -f "$BASENAME"
	run wget -O "$BASENAME" "$URL"
	if [[ "$URL" =~ $regex ]]; then
		run tar xjf "$BASENAME"
	else
		run tar xzf "$BASENAME"
	fi
	run rm "$BASENAME"
}


CONCURRENCY=2
export PATH=/usr/local/override/bin:$PATH

CMAKE_VERSION=3.0.2
OPENSSL_VERSION=1.0.1j
FFI_VERSION=3.2.1
SQLITE3_VERSION=3080702
MYSQL_LIB_VERSION=6.1.5
POSTGRESQL_VERSION=9.3.5


echo "----- chroot entered -----"
cd /tmp
run rm -rf /tmp/*
run rpm --rebuilddb
run yum install -y @development-tools gcc gcc-c++ wget sudo zlib-devel readline-devel
echo


header "Installing CMake..."
if [[ ! -e /usr/local/override/bin/cmake ]]; then
	download_and_extract cmake-$CMAKE_VERSION.tar.gz \
		http://www.cmake.org/files/v3.0/cmake-$CMAKE_VERSION.tar.gz
	echo "Entering cmake-$CMAKE_VERSION"
	pushd cmake-$CMAKE_VERSION >/dev/null

	run ./configure --prefix=/usr/local/override --no-qt-gui --parallel=$CONCURRENCY
	run make -j$CONCURRENCY
	run make install

	echo "Leaving source directory"
	popd >/dev/null
	run rm -rf cmake-$CMAKE_VERSION
fi
echo

header "Installing OpenSSL"
if [[ ! -e /usr/local/override/bin/openssl ]]; then
	download_and_extract openssl-$OPENSSL_VERSION.tar.gz \
		http://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
	echo "Entering openssl-$OPENSSL_VERSION"
	pushd openssl-$OPENSSL_VERSION >/dev/null

	run ./config --prefix=/usr/local/override --openssldir=/usr/local/override/openssl \
		threads zlib no-shared no-sse2 -fPIC -fvisibility=hidden
	run make
	run make install_sw
	run strip --strip-all /usr/local/override/bin/openssl
	run strip --strip-debug /usr/local/override/lib/libcrypto.a
	run strip --strip-debug /usr/local/override/lib/libssl.a
	run sed -i 's/-lcrypto/-lcrypto -ldl/' /usr/local/override/lib/pkgconfig/openssl.pc
	run sed -i 's/-lcrypto/-lcrypto -ldl/' /usr/local/override/lib/pkgconfig/libssl.pc

	echo "Leaving source directory"
	popd >/dev/null
	run rm -rf openssl-$OPENSSL_VERSION
fi
echo

header "Installing libffi"
if [[ ! -e /usr/local/override/lib/libffi.so.6 ]]; then
	download_and_extract libffi-$FFI_VERSION.tar.gz \
		ftp://sourceware.org/pub/libffi/libffi-$FFI_VERSION.tar.gz
	echo "Entering libffi-$FFI_VERSION"
	pushd libffi-$FFI_VERSION >/dev/null

	run ./configure --prefix=/usr/local/override --enable-shared --disable-static \
		--enable-portable-binary
	run make -j$CONCURRENCY
	run make install-strip
	if [[ "$ARCHITECTURE" = x86_64 ]]; then
		run strip --strip-debug /usr/local/override/lib64/libffi.so.6
	else
		run strip --strip-debug /usr/local/override/lib/libffi.so.6
	fi
	
	echo "Leaving source directory"
	popd >/dev/null
	run rm -rf libffi-$FFI_VERSION
fi
echo

if [[ ! -e /usr/local/override/lib/libsqlite3.a ]]; then
	download_and_extract sqlite-autoconf-$SQLITE3_VERSION.tar.gz \
		http://www.sqlite.org/2014/sqlite-autoconf-$SQLITE3_VERSION.tar.gz
	echo "Entering sqlite-autoconf-$SQLITE3_VERSION"
	pushd sqlite-autoconf-$SQLITE3_VERSION >/dev/null

	run ./configure --prefix=/usr/local/override --disable-shared \
		--disable-dynamic-extensions CFLAGS='-fPIC -fvisibility=hidden'
	run make -j$CONCURRENCY
	run make install-strip

	echo "Leaving source directory"
	popd >/dev/null
	run rm -rf sqlite-autoconf-$SQLITE3_VERSION
fi
echo

header "Installing MySQL"
if [[ ! -e /usr/local/override/lib/libmysqlclient.aa ]]; then
	download_and_extract mysql-connector-c-$MYSQL_LIB_VERSION-src.tar.gz \
		http://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-$MYSQL_LIB_VERSION-src.tar.gz
	echo "Entering mysql-connector-c-$MYSQL_LIB_VERSION-src"
	pushd mysql-connector-c-$MYSQL_LIB_VERSION-src >/dev/null

	if [[ "$ARCHITECTURE" = x86 ]]; then
		# Fixes gcc builtin atomics. The default architecture on x86
		# CentOS 5 i386.
		MYSQL_CFLAGS="-march=i586"
	else
		MYSQL_CFLAGS=
	fi
	run cmake -DCMAKE_INSTALL_PREFIX=/usr/local/override \
		-DCMAKE_C_FLAGS="-fPIC -fvisibility=hidden $MYSQL_CFLAGS" \
		-DCMAKE_CXX_FLAGS="-fPIC -fvisibility=hidden $MYSQL_CFLAGS" . \
		-DDISABLE_SHARED=1
	run make -j$CONCURRENCY libmysql
	run make -C libmysql install
	run make -C include install
	run make -C scripts install
	run sed -i "s|^ldflags=''|ldflags='-lstdc++'|"  /usr/local/override/bin/mysql_config

	echo "Leaving source directory"
	popd >/dev/null
	run rm -rf mysql-connector-c-$MYSQL_LIB_VERSION-src
fi
echo

header "Installing PostgreSQL"
if [[ ! -e /usr/local/override/lib/libpq.a ]]; then
	download_and_extract postgresql-$POSTGRESQL_VERSION.tar.bz2 \
		http://ftp.postgresql.org/pub/source/v9.3.5/postgresql-$POSTGRESQL_VERSION.tar.bz2
	echo "Entering postgresql-$POSTGRESQL_VERSION"
	pushd postgresql-$POSTGRESQL_VERSION >/dev/null

	run ./configure --prefix=/usr/local/override CFLAGS="-fPIC -fvisibility=hidden"
	run make -j$CONCURRENCY -C src/common
	run make -j$CONCURRENCY -C src/backend
	run make -j$CONCURRENCY -C src/interfaces/libpq
	run make -C src/interfaces/libpq install-strip
	run make -j$CONCURRENCY -C src/include
	run make -C src/include install-strip
	run make -j$CONCURRENCY -C src/bin/pg_config
	run make -C src/bin/pg_config install-strip
	run rm /usr/local/override/lib/libpq.so*
	
	echo "Leaving source directory"
	popd >/dev/null
	run rm -rf postgresql-$POSTGRESQL_VERSION
fi
echo
