#!/bin/bash
set -e
RUBY_MAJOR=`echo $RUBY_VERSION | cut -d . -f 1`
RUBY_MINOR=`echo $RUBY_VERSION | cut -d . -f 2`
RUBY_MAJOR_MINOR="$RUBY_MAJOR.$RUBY_MINOR"
if [[ "$ARCHITECTURE" = x86 ]]; then
	CHROOT_NAME=epel-5-i386
else
	CHROOT_NAME=epel-5-x86_64
fi

function list_db_files()
{
	file "$@" | grep 'Berkeley DB' | grep 'version 9' | awk '{ print $1 }' | sed 's/:$//'
}

function setup_chroot()
{
	if $INITIALIZE; then
		/system/setuser app /usr/bin/mock -r $CHROOT_NAME --init
	fi
	/system/setuser app /usr/bin/mock -r $CHROOT_NAME --install yum

	# CentOS 6's RPM generates database files which CentOS 5's RPM
	# cannot read, so we fix this. See
	# http://forums.fedoraforum.org/showthread.php?t=222988
	pushd /var/lib/mock/$CHROOT_NAME/root/var/lib/rpm
	rm -fv __db*
	for F in $(list_db_files *); do
		db_dump $F > $F.dump
		rm $F
		db43_load $F < $F.dump
		rm $F.dump
	done
	popd

	cp /system/setup-runtime-inside-mock /var/lib/mock/$CHROOT_NAME/root/
	/system/setuser app /usr/bin/mock -r $CHROOT_NAME --shell /setup-runtime-inside-mock
	rm /var/lib/mock/$CHROOT_NAME/root/setup-runtime-inside-mock
}

echo "---------- Setting permissions -----------"
chown root:mock /var/lib/mock
chmod g+ws /var/lib/mock

echo
echo "---------- Setting up chroot -----------"
(
	set -x
	setup_chroot
)
if [[ $? != 0 ]]; then
	echo "*** Failed setting up chroot"
	exit 1
fi

if $DOWNLOAD_RUBY; then
	echo
	echo "---------- Downloading Ruby -----------"
	rm -f /tmp/ruby.tar.gz
	wget -O /tmp/ruby.tar.gz \
		http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR_MINOR/ruby-$RUBY_VERSION.tar.gz
	cp /tmp/ruby.tar.gz /var/lib/mock/$CHROOT_NAME/root/ruby-$RUBY_VERSION.tar.gz
	rm /tmp/ruby.tar.gz
fi

echo
echo "---------- Setup finished -----------"
