#!/bin/bash
set -e
source /system_shared/library.sh

function list_db_files()
{
	file "$@" | grep 'Berkeley DB' | grep 'version 9' | awk '{ print $1 }' | sed 's/:$//'
}

RUBY_MAJOR=`echo $RUBY_VERSION | cut -d . -f 1`
RUBY_MINOR=`echo $RUBY_VERSION | cut -d . -f 2`
RUBY_MAJOR_MINOR="$RUBY_MAJOR.$RUBY_MINOR"
if [[ "$ARCHITECTURE" = x86 ]]; then
	CHROOT_NAME=epel-5-i386
else
	CHROOT_NAME=epel-5-x86_64
fi
run chown root:mock /var/lib/mock
run chmod g+ws /var/lib/mock
echo

header "Setting up chroot"
if $INITIALIZE; then
	run /system/setuser app /usr/bin/mock -r $CHROOT_NAME --init
fi
run /system/setuser app /usr/bin/mock -r $CHROOT_NAME --install yum
echo

header "Fixing RPM database"
# CentOS 6's RPM generates database files which CentOS 5's RPM
# cannot read, so we fix this. See
# http://forums.fedoraforum.org/showthread.php?t=222988
echo "+ Entering /var/lib/mock/$CHROOT_NAME/root/var/lib/rpm"
pushd /var/lib/mock/$CHROOT_NAME/root/var/lib/rpm >/dev/null
run rm -fv __db*
for F in $(list_db_files *); do
	echo "Fixing $F"
	echo "+ db_dump $F > $F.dump"
	db_dump $F > $F.dump
	run rm $F
	echo "+ db43_load $F < $F.dump"
	db43_load $F < $F.dump
	run rm $F.dump
done
echo "+ Leaving RPM database directory"
popd >/dev/null
echo

echo "Installing additional software inside chroot"
run cp /system/setup-runtime-inside-mock /var/lib/mock/$CHROOT_NAME/root/
run /system/setuser app /usr/bin/mock -r $CHROOT_NAME --shell /setup-runtime-inside-mock
run rm /var/lib/mock/$CHROOT_NAME/root/setup-runtime-inside-mock
echo

if $DOWNLOAD_RUBY; then
	header "Downloading Ruby"
	run rm -f /tmp/ruby.tar.gz
	run wget -O /tmp/ruby.tar.gz \
		http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR_MINOR/ruby-$RUBY_VERSION.tar.gz
	run cp /tmp/ruby.tar.gz /var/lib/mock/$CHROOT_NAME/root/ruby-$RUBY_VERSION.tar.gz
	run rm /tmp/ruby.tar.gz
	echo
fi

header "Finished!"
