# This Gemfile defines all native extensions that Traveling Ruby supports.
# To add a new native extension, add it to this Gemfile, run `bundle install` on
# your workstation (to update the Gemfile.lock), and re-run the Traveling Ruby
# build system.

#source 'http://production.cf.rubygems.org/'
source 'https://rubygems.org'

gem 'nokogiri'
gem 'sqlite3'
gem 'mysql2'
gem 'pg'
gem 'json'
gem 'ffi'
gem 'bcrypt'
gem 'yajl-ruby'
gem 'thin'
gem 'RedCloth'
gem 'escape_utils'
gem 'posix-spawn'
gem 'nokogumbo'
gem 'github-markdown'
gem 'rugged'
gem 'charlock_holmes'
gem 'unf_ext'
