source 'https://rubygems.org'

gem 'json'
gem 'ffi'
gem 'yajl-ruby'
gem 'rexml'
# gem 'fiddle'
gem 'fiddle', git: 'https://github.com/ruby/fiddle'

gem 'bcrypt'
gem 'charlock_holmes', :platforms => :ruby
gem 'curses', :platforms => :ruby
gem 'escape_utils'
gem 'fast-stemmer'
# gem 'ffi'
gem 'hitimes'
# gem 'json'
gem 'kgio', :platforms => :ruby

gem 'nokogiri'
# nokogumbo is now part of nokogiri
gem 'pg'
gem 'posix-spawn', :platforms => :ruby
gem 'puma', :platforms => :ruby
gem 'raindrops', :platforms => :ruby
gem 'redcarpet'
gem 'RedCloth'
gem 'rugged', :platforms => :ruby
# requies 

gem 'sqlite3'
gem 'thin'
gem 'unf_ext'
gem 'unicorn', :platforms => :ruby
# gem 'yajl-ruby'

# gem 'mysql2', :platforms => :ruby
# Fails to build on linux needs to link to zlib