#!/bin/bash
set -e

SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR" && pwd`
source "$SELFDIR/../shared/library.sh"

CPUCOUNT=`"$SELFDIR/internal/cpucount"`
RUBY_VERSIONS=(`cat "$SELFDIR/../RUBY_VERSIONS.txt"`)

RUNTIME_DIR=
OUTPUT_DIR=
ARCHITECTURE=
RUBY_VERSION=${RUBY_VERSIONS[0]}
CONCURRENCY=$CPUCOUNT
GEMFILE="$SELFDIR/../shared/gemfiles"
SETUP_SOURCE=true
COMPILE=true
SANITY_CHECK_OUTPUT=true
GEMFILE_MOUNT=()

function usage()
{
	echo "Usage: ./build-ruby [options] <RUNTIME DIR> <OUTPUT_DIR>"
	echo "Build Traveling Ruby binaries."
	echo
	echo "Options:"
	echo "  -a NAME     Architecture to setup (x86, x86_64)"
	echo "  -r VERSION  Ruby version to build. Default: $RUBY_VERSION"
	echo
	echo "  -E          Do not setup source"
	echo "  -C          Do not compile Ruby"
	echo "  -G          Do not install gems"
	echo
	echo "  -j NUMBER   Set build concurrency. Default: $CPUCOUNT"
	echo "  -g PATH     Build gems as specified by the given Gemfile"
	echo "  -h          Show this help"
}

function parse_options()
{
	local OPTIND=1
	local opt
	while getopts "a:r:ECGj:g:h" opt; do
		case "$opt" in
		a)
			ARCHITECTURE=$OPTARG
			;;
		r)
			RUBY_VERSION=$OPTARG
			;;
		E)
			SETUP_SOURCE=false
			;;
		C)
			COMPILE=false
			;;
		G)
			GEMFILE=
			;;
		j)
			CONCURRENCY=$OPTARG
			;;
		g)
			GEMFILE="$OPTARG"
			;;
		h)
			usage
			exit
			;;
		*)
			return 1
			;;
		esac
	done

	(( OPTIND -= 1 )) || true
	shift $OPTIND || true
	RUNTIME_DIR="$1"
	OUTPUT_DIR="$2"

	if [[ "$RUNTIME_DIR" = "" || "$OUTPUT_DIR" = "" ]]; then
		usage
		exit 1
	fi
	if [[ ! -e "$RUNTIME_DIR" ]]; then
		echo "ERROR: $RUNTIME_DIR doesn't exist."
		exit 1
	fi
	if [[ ! -e "$OUTPUT_DIR" ]]; then
		echo "ERROR: $OUTPUT_DIR doesn't exist."
		exit 1
	fi
	if [[ "$ARCHITECTURE" = "" ]]; then
		echo "ERROR: please specify an architecture with -a."
		exit 1
	fi
}


parse_options "$@"
RUNTIME_DIR=`cd "$RUNTIME_DIR" && pwd`
OUTPUT_DIR=`cd "$OUTPUT_DIR" && pwd`
if [[ ! -e "$RUNTIME_DIR/mock" ]]; then
	echo "ERROR: runtime directory $RUNTIME_DIR not set up. Please run ./setup-runtime first."
	exit 1
fi
if [[ "$GEMFILE" != "" ]]; then
	GEMFILE="`absolute_path \"$GEMFILE\"`"
	if [[ -d "$GEMFILE" ]]; then
		for F in "$GEMFILE"/*/Gemfile; do
			DIR="`dirname \"$F\"`"
			DIR="`basename \"$DIR\"`"
			GEMFILE_MOUNT+=(-v "$F:/gemfiles/$DIR/Gemfile:ro")
			if [[ -e "$F.lock" ]]; then
				GEMFILE_MOUNT+=(-v "$F.lock:/gemfiles/$DIR/Gemfile.lock:ro")
			fi
		done
	else
		GEMFILE_MOUNT=(-v "$GEMFILE:/gemfiles/default/Gemfile:ro")
		if [[ -e "$GEMFILE.lock" ]]; then
			GEMFILE_MOUNT+=(-v "$GEMFILE.lock:/gemfiles/default/Gemfile.lock:ro")
		fi
	fi
fi

exec docker run \
	--rm \
	--cap-add SYS_ADMIN --cap-add SYS_CHROOT \
	-v "$SELFDIR/internal:/system:ro" \
	-v "$SELFDIR/../shared:/system_shared:ro" \
	-v "$RUNTIME_DIR/mock:/var/lib/mock" \
	-v "$OUTPUT_DIR:/output" \
	"${GEMFILE_MOUNT[@]}" \
	-e "APP_UID=`id -u`" \
	-e "APP_GID=`id -g`" \
	-e "RUBY_VERSION=`cat \"$SELFDIR/../RUBY_VERSION.txt\"`" \
	-e "BUNDLER_VERSION=`cat \"$SELFDIR/../BUNDLER_VERSION.txt\"`" \
	-e "ARCHITECTURE=$ARCHITECTURE" \
	-e "RUBY_VERSION=$RUBY_VERSION" \
	-e "CONCURRENCY=$CONCURRENCY" \
	-e "SETUP_SOURCE=$SETUP_SOURCE" \
	-e "COMPILE=$COMPILE" \
	-e "SANITY_CHECK_OUTPUT=$SANITY_CHECK_OUTPUT" \
	phusion/traveling-ruby-builder \
	/system/my_init --quiet --skip-runit --skip-startup-files -- \
	/system/build-ruby
