#!/bin/bash
set -e

SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR" && pwd`

RUNTIME_DIR=
INITIALIZE=true
DOWNLOAD_RUBY=true

function usage()
{
	echo "Usage: ./setup-runtime [options] <RUNTIME DIR>"
	echo "Sets up the Traveling Ruby build system's runtime."
	echo
	echo "Options:"
	echo "  -i      Only initialize chroot environment"
	echo "  -I      Do not initialize chroot environments"
	echo "  -r      Only download Ruby"
	echo "  -R      Do not download Ruby"
	echo "  -h      Show this help"
}

function parse_options()
{
	local OPTIND=1
	local opt
	while getopts "iIrRh" opt; do
		case "$opt" in
		i)
			INITIALIZE=true
			DOWNLOAD_RUBY=false
			;;
		I)
			INITIALIZE=false
			;;
		r)
			INITIALIZE=false
			DOWNLOAD_RUBY=true
			;;
		R)
			DOWNLOAD_RUBY=false
			;;
		h)
			usage
			exit
			;;
		*)
			return 1
			;;
		esac
	done

	(( OPTIND -= 1 )) || true
	shift $OPTIND || true
	RUNTIME_DIR="$1"

	if [[ "$RUNTIME_DIR" = "" ]]; then
		usage
		exit 1
	fi
	if [[ ! -e "$RUNTIME_DIR" ]]; then
		echo "ERROR: $RUNTIME_DIR doesn't exist."
		exit 1
	fi
}


parse_options "$@"
RUNTIME_DIR=`cd "$RUNTIME_DIR" && pwd`
mkdir -p "$RUNTIME_DIR/mock"

exec docker run \
	--rm \
	--cap-add SYS_ADMIN --cap-add SYS_CHROOT \
	-v "$SELFDIR/internal:/system:ro" \
	-v "$SELFDIR/../shared:/system_shared:ro" \
	-v "$RUNTIME_DIR/mock:/var/lib/mock" \
	-e "INITIALIZE=$INITIALIZE" \
	-e "DOWNLOAD_RUBY=$DOWNLOAD_RUBY" \
	phusion/ruby-traveler-builder \
	/system/my_init --quiet --skip-runit --skip-startup-files -- \
	/system/setup-runtime
