#!/bin/bash
set -e

function cleanup()
{
	set +e
	local pids=`jobs -p`
	if [[ "$pids" != "" ]]; then
		kill $pids >/dev/null
	fi
	if [[ "$TEMPDIR" != "" ]]; then
		rm -rf "$TEMPDIR"
	fi
}

trap cleanup EXIT

SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR" && pwd`
TEMPDIR=

if [[ $# == 0 ]]; then
	echo "Usage: ./upload <FILES>"
	echo "Uploads files to Amazon S3."
	exit 1
fi

if [[ ! -e ~/.s3cfg ]]; then
	echo "~/.s3cfg doesn't exist; configuring one..."
	TEMPDIR=`mktemp -d /tmp/traveling-ruby.XXXXXXXX`
	touch "$TEMPDIR/s3cfg"
	docker run --rm -t -i \
		-v "$SELFDIR/internal:/system:ro" \
		-v "$TEMPDIR:/work" \
		phusion/ruby-traveler-builder \
		/system/my_init --quiet --skip-runit --skip-startup-files -- \
		/system/s3configure
	cp "$TEMPDIR/s3cfg" ~/.s3cfg
	rm -rf "$TEMPDIR"
	TEMPDIR=
fi

MOUNTS=()
BASENAMES=()
for F in "$@"; do
	DIR="`dirname \"$F\"`"
	DIR="`cd \"$DIR\" && pwd`"
	BASENAME="`basename \"$F\"`"
	F="$DIR/$BASENAME"
	
	MOUNTS+=(-v "$F:/$BASENAME:ro")
	BASENAMES+=("$BASENAME")
done

echo "Uploading ${BASENAMES[@]} to Amazon S3..."
S3CFG="`echo ~/.s3cfg`"
exec docker run --rm -t -i \
	"${MOUNTS[@]}" \
	-v "$S3CFG:/s3cfg:ro" \
	-v "$SELFDIR/internal:/system:ro" \
	phusion/ruby-traveler-builder \
	/system/my_init --quiet --skip-runit --skip-startup-files -- \
	/system/s3init \
	s3cmd -P put "${BASENAMES[@]}" s3://traveling-ruby/releases/
