source 'https://rubygems.org'

gem 'bcrypt'
gem 'charlock_holmes', :platforms => :ruby
gem 'curses', :platforms => :ruby
gem 'escape_utils'
gem 'fast-stemmer'
gem 'ffi'
gem 'hitimes'
gem 'json'
gem 'kgio', :platforms => :ruby
gem 'mysql2', :platforms => :ruby
gem 'nokogiri'
gem 'nokogumbo', '~> 1.5.0'
gem 'pg'
gem 'posix-spawn', :platforms => :ruby
gem 'puma', :platforms => :ruby
gem 'raindrops', :platforms => :ruby
gem 'redcarpet'
gem 'RedCloth'
gem 'rugged', :platforms => :ruby
gem 'sqlite3'
gem 'thin'
gem 'unf_ext'
gem 'unicorn', :platforms => :ruby
gem 'yajl-ruby'
